var sessions = [
    {id:0 , title:"8:00 AM", isDivider:true},
	{id:1 , title:"History of the Center of the Universe", 
    		speaker:"J MARTIN", 
    		position:"", 
    		aboutspeaker:"About speaker.", 
    		gender:"M", 
    		day:"4", month:"May", year:"2016", hourblock:"8:00 AM", 
    		starttime:"8:00am", endtime:"8:25am", 
    		room:"DGTC Auditorium", 
    		description: "In this session, you'll learn how to build a native-like mobile application using the Ionic Framework, AngularJS, and Cordova.", 
    		webex: "https://walmart.webex.com/walmart/j.php?MTID=m52b82b601c680eee2eef642de46386f1", webexNum: "", webexPwd: "", 
    		avatar:""},
	{id:2 , title:"Industry transformation of IOT", 
    		speaker:"JOHN COHN", 
    		position:"", 
    		aboutspeaker:"About speaker.", 
    		gender:"M", 
    		day:"2", month:"June", year:"2016", hourblock:"8:00 AM", 
    		starttime:"8:30am", endtime:"8:55am", 
    		room:"DGTC Auditorium", 
    		description: "In this session, you'll learn everything you need to know to start building next-gen JavaScript applications using AngularJS.", 
    		webex: "https://walmart.webex.com/walmart/j.php?MTID=m52b82b601c680eee2eef642de46386f1", webexNum: "", webexPwd: "", 
    		avatar:""},
	{id:3 , title:"9:00 AM", isDivider:true},
	{id:4 , title:"CYBERSAFE – How the Digital World is Changing the Way We Think About National Security", 
			speaker:"ADMIRAL JAMES RODMAN", 
			position:"Chief Engineer, Space and Naval Warfare Systems Command", 
			aboutspeaker:"Rear Adm. Rodman served in multiple technical and leadership assignments in ship, space, C4ISR, and cyber systems acquisition, operations, and maintenance. " +
				"He commanded three reserve component units Naval Weapons Station Earle Detachment 601 EOT, Naval Network Warfare Command Network Engineering, and Space and Naval Warfare Systems Command 0466. " +
				"He also served multiple acquisition and operational tours at the National Reconnaissance Office. In 2008 he served as the Space Domain director on the national staff of the Navy Net-Centric Warfare Group (NNWG) and in 2009 was named NNWG’s vice commander.", 
			gender:"M", 
			day:"2", month:"June", year:"2016", hourblock:"9:00 AM", 
			starttime:"9:00am", endtime:"9:25am", 
			room:"DGTC Auditorium", 
			description: "Cybersafety is the safe and responsible use of information and communication technology. " +
				"It is about keeping information safe and secure, but also about being responsible with that information always protecting data from destructive forces and from the unwanted actions of unauthorized users.", 
			webex: "https://walmart.webex.com/walmart/j.php?MTID=m52b82b601c680eee2eef642de46386f1", webexNum: "", webexPwd: "", 
			avatar:"http://beinsure.com.mx/techlive/img/img1.jpg"},
	{id:5 , title:"Mobile Marketing and Gamification", 
			speaker:"JENNIFER WISE", 
			position:"", 
			aboutspeaker:"About speaker.", 
			gender:"F", 
			day:"2", month:"June", year:"2016", hourblock:"9:00 AM", 
			starttime:"9:30am", endtime:"9:55pm", 
			room:"DGTC Auditorium", 
			description: "In this session, you will learn performance techniques to speed up your mobile application.", 
			webex: "https://walmart.webex.com/walmart/j.php?MTID=m52b82b601c680eee2eef642de46386f1", webexNum: "", webexPwd: "", 
			avatar:""},
    {id:6 , title:"10:00 AM", isDivider:true},
	{id:7 , title:"Building Modular Applications", 
    		speaker:"LAURA TAYLOR", 
    		position:"", 
    		aboutspeaker:"About speaker.", 
    		gender:"F", 
    		day:"2", month:"June", year:"2016", hourblock:"10:00 AM", 
    		starttime:"10:00am", endtime:"10:25am", 
    		room:"DGTC Auditorium", 
    		description: "Join Laura to learn different approaches to build modular JavaScript applications.", 
    		webex: "https://walmart.webex.com/walmart/j.php?MTID=m52b82b601c680eee2eef642de46386f1", webexNum: "", webexPwd: "", 
    		avatar:""},
	{id:8 , title:"Panel", 
    		speaker:"GERSON MONTIEL, LUIS RODRIGUEZ, JULIAN VALENCIA", 
    		position:"", 
    		aboutspeaker:"About speaker.", 
    		gender:"M", 
    		day:"2", month:"June", year:"2016", hourblock:"10:00 AM", 
    		starttime:"10:30am", endtime:"11:00am", 
    		room:"DGTC Auditorium", 
    		description: "Learn the capabilities of having a real analitycs platform.", 
    		webex: "https://walmart.webex.com/walmart/j.php?MTID=m52b82b601c680eee2eef642de46386f1", webexNum: "", webexPwd: "", 
    		avatar:""}
	];

exports.findAll = function (req, res, next) {
    res.send(sessions);
};

exports.findById = function (req, res, next) {
    var id = req.params.id;
    res.send(sessions[id]);
};